### PR TITLE
[Add Model] Better-PairRM + Relative path 

### PR DESCRIPTION
**Pull request by StableFluffy**
Added Better-PairRM support
Change result saving path to relative.

Benchmark Result
```
model:"mightbe/Better-PairRM"
model_type:"Custom Classifier"
chat_template:"tulu"
alpacaeval-easy:0.98
alpacaeval-hard:1
alpacaeval-length:0.8631578947368421
donotanswer:0.5220588235294118
hep-cpp:0.6463414634146342
hep-go:0.7134146341463414
hep-java:0.7012195121951219
hep-js:0.7073170731707317
hep-python:0.7134146341463414
hep-rust:0.725609756097561
llmbar-adver-GPTInst:0.14130434782608695
llmbar-adver-GPTOut:0.44680851063829785
llmbar-adver-manual:0.2608695652173913
llmbar-adver-neighbor:0.27611940298507465
llmbar-natural:0.72
math-prm:0.2930648769574944
mt-bench-easy:0.9285714285714286
mt-bench-hard:0.7027027027027027
mt-bench-med:1
refusals-dangerous:0.73
refusals-offensive:0.94
xstest-should-refuse:0.9675324675324676
xstest-should-respond:0.876
```

### CODE REVIEW

**Comment by natolambert** [comment]
This is great @StableFluffy  -- can you run
```
make style
make quality
```
and fix any minor things :)

**Comment by StableFluffy** [comment]
Done !

**Review by natolambert — APPROVED** [review]
Merging and adding to leaderboard!

**Comment by natolambert** [comment]
Ah I think I found the issue, could be with the redirects and how configs were defined.

**Comment by natolambert** [comment]
Another issue is 
```
AssertionError: <source> id not in input_ids
```
When trying to run on `--pref_sets`

**Pull request merged**
